REFINED: - set continue on error - use new scipts ADDED: - refactor deploy scripts no more duplicated script with single responsibility followed SoC

diff --git a/.github/workflows/staging.yml b/.github/workflows/staging.yml
--- a/.github/workflows/staging.yml
+++ b/.github/workflows/staging.yml
@@ -17,6 +17,7 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Setup SSH Connection
+        continue-on-error: true
         run: |
           echo "Setting up SSH connection..."
           mkdir -p ~/.ssh
@@ -39,7 +40,7 @@ jobs:
             cd ~/WealthTracking || { echo "Failed to navigate to project directory"; exit 1; }
             
             echo "Executing deploy script..."
-            ./deploy.sh ${{ secrets.STAGING_SERVERS_IP }} 3000 || { echo "Deployment script failed"; exit 1; }
+            ./scripts/deploy.sh ${{ secrets.STAGING_SERVERS_IP }} || { echo "Deployment script failed"; exit 1; }
             
             echo "Deployment completed successfully."
           EOF
